modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/buriedwrecks/issues"
license="MIT"

[[mods]]
modId="buriedwrecks"
version="${file.jarVersion}"
displayName="Buried Wrecks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/buriedwrecks"
authors="Mrbysco"
description='''
What sort of music did cave men listen to? Hard Rock!
'''
[[dependencies.buriedwrecks]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"