modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/buriedwrecks/issues"
license="MIT"

[[mods]]
modId="buriedwrecks"
version="${file.jarVersion}"
displayName="Buried Wrecks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/buriedwrecks"
authors="Mrbysco"
description='''
What sort of music did cave men listen to? Hard Rock!
'''
[[dependencies.buriedwrecks]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.buriedwrecks]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"